source = ~/.config/hypr/conf/programs.conf

exec-once = dunst
exec-once = waybar
exec-once = ~/Documents/system/update-prompt/startup_update_prompt.sh
exec-once = awww-daemon
exec-once = wal-tile "./three.jpeg"
